name: Codepenguin
description: Blogging about code and stuff
meta_description: "Blogging about code and stuff"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
