name: Codepenguin
description: Blogging about code and stuff
meta_description: "Blogging about code and stuff"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://codepengu.in'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://codepengu.in'
author:         'The CodePenguin'
